### ISSUE TITLE
Add an option to open with MPlayerX

### ISSUE THREAD

**Issue by AndrewSB** [asarode/termflix#1]
Similar to the `--vlc` argument, I think you should add a flag that opens with MPlayerX (`--mplayerx`)

**Comment by asarode** [comment]
Hm, running `peerflix [magnet] --mplayerx` or `peerflix [magnet] --mplayer` isn't opening the magnet link for me. Is it working for you?

I'm planning on putting a separate prompt that asks the user which player they want to open the selected torrent with. I'll make it so it's super simple to add support for any player option peerflix supports.

**Comment by AndrewSB** [comment]
I dont think peerflix's `--mplayer` flag works with OSX's MplayerX. My bad, I thought that would just work

**Comment by AndrewSB** [comment]
add termflix to npm doe

**Comment by asarode** [comment]
It should be on there. Here's the link: https://www.npmjs.com/package/termflix
