### ISSUE TITLE
Can't stream on Debian Jessie

### ISSUE THREAD

**Issue by baydam** [asarode/termflix#11]
? Enable marathon mode for these files? Yes
Enabled marathon! Just run `termflix marathon` to select the next file!

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

**Comment by asarode** [comment]
Hey, thanks for letting me know about this. It looks like it can't spawn peerflix. Did you install peerflix globally already? If not, just do `npm install -g peerflix` and then try using termflix again.

**Comment by asarode** [comment]
Ah, I'm getting an error too now. I'll look into it more.
